In [6]:
#using any and all
import numpy as np

In [3]:
ar=np.array([1,2,3,0])
ar1=np.array([0,2,3,1])
res=ar>ar1
print('Result of ar>ar1 :',res)
print('Check if any one element is true:',any(res))
print('Check if all elements are true:',all(res))
#if (any(ar>ar1))

Result of ar>ar1 : [ True False False False]
Check if any one element is true: True
Check if all elements are true: False


In [4]:
#logical_and(),logical_or(),logical_not()
ar=np.array([1,2.0,3,0],int)        #ar>0: true,true,true,false  #ar<4: true,true,true,true
ar1=np.array([0,2.0,3,1],int)
c=np.logical_and(ar>0,ar<4)    
print(c)                        

[ True  True  True False]


In [3]:
#logical_or()
ar=np.array([1,2.0,3,0],int)               #ar>0 true,true,true,false    #ar<4: true,true,true,true
ar1=np.array([0,2.0,3,1],int)    
c=np.logical_or(ar>0,ar<4)
print(c)

[ True  True  True  True]


In [8]:
#logical_not()                         #NOT - IF IT IS ZERO ,THEN TRUE
ar1=np.array([0,1.0,1,0],int)         #ar1=true,false ,fALSE ,TRUE
c=np.logical_not(ar1)
print(c)

[ True False False  True]


In [10]:
#Transpose of a matrix (Array)
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print('Original array is:')
print(a)
print('*'*20)
print('Transpose of a Array is:')
print(a.transpose())


Original array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
********************
Transpose of a Array is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
#Transpose of a matrix (Array)
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print('Original array is:')
print(a)
print('*'*20)
print('Transpose of a Array is:')
print(a.T)

Original array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
********************
Transpose of a Array is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
#full function is used to create a numpy array filled with a specified constant value
import numpy as np
twos=np.full(5,2)
print(twos)

[2 2 2 2 2]


In [19]:
twos=np.full(5,3)
print(twos)

[3 3 3 3 3]


In [14]:
emp=np.empty((3,3))
print(emp)
print('*'*25)
emp.fill(5)
print(emp)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.35169681e-321]
 [3.11525958e-307 1.24610723e-306 1.29516345e-318]]
*************************
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [26]:
iden=np.eye(5,k=1,dtype='int')*5
print(iden)

[[0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]
 [0 0 0 0 0]]


In [17]:
iden=np.eye(5,dtype='int')*10
print(iden)

[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]


In [18]:
#linspace - It allows you to do customize the range to fit your specific needs.
#linespace - stop and stop two parameters are required
lin=np.linspace(1,10)
print(lin)
print(lin.dtype)
print(lin.shape)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
float64
(50,)


In [21]:
lin=np.linspace(1,5)
print(lin)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [19]:
lin=np.linspace(1,25,5)
print(lin)

[ 1.  7. 13. 19. 25.]


In [3]:
lin=np.linspace(2,9)
print(lin)

[2.         2.14285714 2.28571429 2.42857143 2.57142857 2.71428571
 2.85714286 3.         3.14285714 3.28571429 3.42857143 3.57142857
 3.71428571 3.85714286 4.         4.14285714 4.28571429 4.42857143
 4.57142857 4.71428571 4.85714286 5.         5.14285714 5.28571429
 5.42857143 5.57142857 5.71428571 5.85714286 6.         6.14285714
 6.28571429 6.42857143 6.57142857 6.71428571 6.85714286 7.
 7.14285714 7.28571429 7.42857143 7.57142857 7.71428571 7.85714286
 8.         8.14285714 8.28571429 8.42857143 8.57142857 8.71428571
 8.85714286 9.        ]


In [34]:
#logospace
log=np.logspace(1,3,5) #10 power 1 to 10 to power 4 into 5 equal parts
print(log)


[  10.           31.6227766   100.          316.22776602 1000.        ]


In [23]:
log=np.logspace(3,5,10) #10 power 1 to 10 to power 4 into 5 equal parts
print(log)

[  1000.           1668.1005372    2782.55940221   4641.58883361
   7742.63682681  12915.49665015  21544.34690032  35938.13663805
  59948.42503189 100000.        ]


In [5]:
#1-D to 3-D array conversion
arr=np.arange(12)
print('1-D Array is:')
print(arr)
print('*'*30)
ar_3d=arr.reshape(2,3,2)
print('3-D Array is:')
print(ar_3d)

1-D Array is:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
******************************
3-D Array is:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [25]:
print(ar_3d.ndim)
print(ar_3d.size)
print(ar_3d.shape)

3
12
(2, 3, 2)


In [26]:
ar_3d=arr.reshape(1,3,4)
print('3-D Array is:')
print(ar_3d)

3-D Array is:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [13]:
ar_3d=arr.reshape(1,4,3)
print(ar_3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


In [8]:
ar_3d=arr.reshape(2,2,3)  #no.of.dimensions /no.of.rows/no.of.
print('3-D Array is:')
print(ar_3d)

3-D Array is:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [28]:
print(ar_3d[0:3])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [29]:
print(ar_3d[0:2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [30]:
print(ar_3d[0:1])

[[[0 1 2]
  [3 4 5]]]


In [3]:
emp=np.empty((3,3))
print(emp)
print('*'*25)
emp.fill(2)
print(emp)

[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 7.37e-321]
 [0.00e+000 0.00e+000 0.00e+000]]
*************************
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [4]:
emp=np.empty((4,3))
print(emp)
print('*'*25)
emp.fill(2)
print(emp)

[[9.08507049e-312 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.17381422e+165]
 [9.59723050e-071 4.95515898e-062 2.96184427e-032]
 [2.23044544e+160 1.34967864e+161 4.08675077e-033]]
*************************
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
arr=np.array[1,2,3,4,5,6,7,8]


In [5]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print('Original array is:')
print(a)
print('*'*20)




Original array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
********************


In [10]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print('Original array is:')
print(a)
print('*'*20)
np.flip(a)


Original array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
********************


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [17]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a1=a.reshape(5,2)
print(a1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [12]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a[1:,1:])

[[5 6]
 [8 9]]


In [13]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a[1][2])

6


In [26]:
import numpy as np
l=np.arange(5)
l[0:3]=4
print(l)

[4 4 4 3 4]


In [27]:
import numpy as np
l=np.arange(5)
l[0:3]=4
print(l)

[4 4 4 3 4]


In [30]:
arr=np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [31]:
part_arr=arr[0:5]
part_arr

array([0, 1, 2, 3, 4])

In [35]:
part_arr=arr[5:9]
part_arr

array([6, 6, 6, 6])

In [36]:
part_arr[:]=6
part_arr

array([6, 6, 6, 6])

In [37]:
arr

array([ 0,  1,  2,  3,  4,  6,  6,  6,  6,  9, 10])

In [41]:
copy_arr=arr[2:5].copy()
print(copy_arr)

[2 3 4]


In [47]:
arr<45


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])