In [1]:
Pandas :

-panel data system and python data analysis

It has functions,cleaning exploring and manufactoring data

It was created by wes Mckinney in 2008

Two types in pandas

1.series - It is a one -dimensional array holding data of any type. It is like a coloumn in a table
2.Data frame- It is used for 2-D or more dimensional array table generation


SyntaxError: invalid syntax (1745055372.py, line 1)

In [141]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame


In [6]:
ar=np.array([12,90,54,56])
print(ar)
print(type(ar))

[12 90 54 56]
<class 'numpy.ndarray'>


In [7]:
ser=pd.Series(ar)
ser

0    12
1    90
2    54
3    56
dtype: int32

In [8]:
ser=pd.Series(data=ar,index=['A','B','C','D'])
ser

A    12
B    90
C    54
D    56
dtype: int32

In [9]:
#to access the series table values
print(ser[0])


12


In [10]:
print(ser['A'])

12


In [127]:
ar1=np.arange(8,dtype=float)
print(ar1)
print('*'*20)
ser1=pd.Series(ar1)
ser1

[0. 1. 2. 3. 4. 5. 6. 7.]
********************


0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
dtype: float64

In [120]:
ar2=np.array(['suba','maha','nasrin'])
print(ar2)
print(ar2.dtype)

['suba' 'maha' 'nasrin']
<U6


In [13]:
ser2=pd.Series(ar2)
print(ser2)

0      suba
1      maha
2    nasrin
dtype: object


In [14]:
#To create a series using Dictionary
data={'subha ':'developer','maha':'analyst','nasrin':'scientist'}
se=pd.Series(data)
se

subha     developer
maha        analyst
nasrin    scientist
dtype: object

In [15]:
se=pd.Series(data,name='database')
se

subha     developer
maha        analyst
nasrin    scientist
Name: database, dtype: object

In [16]:
ran=np.random.randint(0,15,5)
ser=pd.Series(ran)
print(ser)

0     1
1    14
2    10
3     8
4     6
dtype: int32


In [17]:
ran=np.random.randint(0,15,5)
ser=pd.Series(ran)
print(ser)

0     3
1     1
2    11
3     5
4     6
dtype: int32


In [18]:
ran=np.random.randn(9)
ser=pd.Series(ran)
print(ser)

0   -0.379602
1   -1.297676
2   -0.719285
3   -0.932288
4    1.694972
5    0.119738
6   -0.918761
7    1.403211
8    0.420195
dtype: float64


In [19]:
ran=np.random.rand(9)
ser=pd.Series(ran)
print(ser)

0    0.707533
1    0.964274
2    0.452867
3    0.755290
4    0.212586
5    0.919173
6    0.654860
7    0.769890
8    0.818819
dtype: float64


In [20]:
#creating a series from scalar values


In [21]:
ser3=pd.Series(data=3,index=['a','b','c','d'])
ser3

a    3
b    3
c    3
d    3
dtype: int64

In [22]:
dic={'A':3,'B':2.58,'C':3.25,'D':3.00}
ser=pd.Series(dic)
ser

A    3.00
B    2.58
C    3.25
D    3.00
dtype: float64

In [23]:
ser['A']

3.0

In [24]:
ser[['A','B']]
ser

A    3.00
B    2.58
C    3.25
D    3.00
dtype: float64

In [25]:
ser>3

A    False
B    False
C     True
D    False
dtype: bool

In [26]:
ser[ser>3]                      #@

C    3.25
dtype: float64

In [27]:
'B' in ser


True

In [28]:
'A' in ser


True

In [29]:
ser.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [30]:
ser.values

array([3.  , 2.58, 3.25, 3.  ])

In [31]:
#arithmetic operations
ser1=pd.Series([2.0,3.0,2.5,2.0])
ser1

0    2.0
1    3.0
2    2.5
3    2.0
dtype: float64

In [32]:

ser2=pd.Series([2.0,3.0,2.5,2.0],index=['A','B','C','D'])
ser2


A    2.0
B    3.0
C    2.5
D    2.0
dtype: float64

In [33]:
ser

A    3.00
B    2.58
C    3.25
D    3.00
dtype: float64

In [34]:
ser1+ser2

0   NaN
1   NaN
2   NaN
3   NaN
A   NaN
B   NaN
C   NaN
D   NaN
dtype: float64

In [35]:
ar=pd.Series([np.nan,10.54,np.nan,35])
print(ar)

0      NaN
1    10.54
2      NaN
3    35.00
dtype: float64


In [36]:
ar=pd.Series([np.nan,10.54,np.nan,35])
print(ar)

0      NaN
1    10.54
2      NaN
3    35.00
dtype: float64


In [37]:
ar=pd.Series([np.nan,10,np.nan])
ar

0     NaN
1    10.0
2     NaN
dtype: float64

In [38]:
ser1=pd.Series(data=3,index=[1,2,34,4])
ser1

1     3
2     3
34    3
4     3
dtype: int64

In [39]:
import numpy as np
import pandas as pd
ar.isnull()

0     True
1    False
2     True
dtype: bool

In [40]:
#replace - change value in replace function
ser=pd.Series(np.arange(10))
ser

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [41]:
ser=pd.Series(np.arange(2,10))
ser

0    2
1    3
2    4
3    5
4    6
5    7
6    8
7    9
dtype: int32

In [42]:
ser.replace(0,'$')
ser

0    2
1    3
2    4
3    5
4    6
5    7
6    8
7    9
dtype: int32

In [43]:
ser

0    2
1    3
2    4
3    5
4    6
5    7
6    8
7    9
dtype: int32

In [44]:
ser.replace(3,'&',inplace=True)
ser


0    2
1    &
2    4
3    5
4    6
5    7
6    8
7    9
dtype: object

In [45]:
ser

0    2
1    &
2    4
3    5
4    6
5    7
6    8
7    9
dtype: object

In [46]:
ser.replace(5,'&',inplace=True)
ser
ser

0    2
1    &
2    4
3    &
4    6
5    7
6    8
7    9
dtype: object

In [47]:
ser.replace(['&',6],[11,12],inplace=True)
ser

0     2
1    11
2     4
3    11
4    12
5     7
6     8
7     9
dtype: int64

In [48]:
ser.replace({2:15},inplace=True)   #dictionary method
ser

0    15
1    11
2     4
3    11
4    12
5     7
6     8
7     9
dtype: int64

In [49]:
ser.replace(4,method='bfill')   #bfilll--->  fill the values in forward

0    15
1    11
2    11
3    11
4    12
5     7
6     8
7     9
dtype: int64

In [50]:
ser.replace(12,method='ffill')   #bfill---> fill the values in forwards


0    15
1    11
2     4
3    11
4    11
5     7
6     8
7     9
dtype: int64

In [51]:
#dataframe - are actually multiple series sharing the samee index .Dataframe are very important when it comes to large
#datasets
#it can generate table for one or more dimensional arrays

In [52]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [123]:
li=[1,4,5,6],[9,8,10,12]
print(li)
print(type(li))

([1, 4, 5, 6], [9, 8, 10, 12])
<class 'tuple'>


In [125]:
#to change the list into dataframe
df=DataFrame(data=li)
df

0  1   2   3
0  1  4   5   6
1  9  8  10  12

In [55]:
df[0]

0    1
1    9
Name: 0, dtype: int64

In [56]:
#to change the list into dataframe
df=DataFrame(data=li,index=['row1','row2'],columns=['col1','col2','col3','col4'])
df

col1  col2  col3  col4
row1     1     4     5     6
row2     9     8    10    12

In [57]:
#to change array value in dataframe
ar=np.arange(8)
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [142]:
ar1=ar.reshape(2,4)
ar1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [143]:
df1=DataFrame(ar1,index=['R1','R2'],columns=['C1','C2','C3','C4'])
df1

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7

In [144]:
df1['C1']

R1    0
R2    4
Name: C1, dtype: int32

In [145]:
#to select the list of columns
df1[['C1','C3']]

C1  C3
R1   0   2
R2   4   6

In [146]:
#selecting the rows
1) loc - enter index label
2)iloc - enter the index  number


SyntaxError: unmatched ')' (137285701.py, line 2)

In [147]:
df1

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7

In [148]:
df1.loc['R1']

C1    0
C2    1
C3    2
C4    3
Name: R1, dtype: int32

In [149]:
df1.iloc[1]


C1    4
C2    5
C3    6
C4    7
Name: R2, dtype: int32

In [150]:
#conditional selection (masking)
df1>5

C1     C2     C3     C4
R1  False  False  False  False
R2  False  False   True   True

In [151]:
df1[df1>5]

C1  C2   C3   C4
R1 NaN NaN  NaN  NaN
R2 NaN NaN  6.0  7.0

In [173]:
df1[(df1['C1']>3) | (df1['C1']==1)]

C1  C2  C3  C4
R2   4   5   6   7

In [153]:
df1[(df1['C1']>3)  & (df1['C1']==1)]

Empty DataFrame
Columns: [C1, C2, C3, C4]
Index: []

In [154]:
#to convert dictionary into dataframe
df2=DataFrame({
    'Name':['Suba','maha','nasrin','keerthi','selvi'],
    'Degree':['B.sc','MBA','B.E','B.E','BCA'],
    'Salary':[35000,40000,50000,42000,45000]
})
df2


Name Degree  Salary
0     Suba   B.sc   35000
1     maha    MBA   40000
2   nasrin    B.E   50000
3  keerthi    B.E   42000
4    selvi    BCA   45000

In [155]:
df2.replace({'Name':{'Suba':'mathu','maha':'nasrin'}},inplace=True)
df2            

Name Degree  Salary
0    mathu   B.sc   35000
1   nasrin    MBA   40000
2   nasrin    B.E   50000
3  keerthi    B.E   42000
4    selvi    BCA   45000

In [156]:
df2.index

RangeIndex(start=0, stop=5, step=1)

In [157]:
df2.columns

Index(['Name', 'Degree', 'Salary'], dtype='object')

In [158]:
df2.sort_values(by='Name')
df2

Name Degree  Salary
0    mathu   B.sc   35000
1   nasrin    MBA   40000
2   nasrin    B.E   50000
3  keerthi    B.E   42000
4    selvi    BCA   45000

In [159]:
df1=DataFrame({
    'Name': ['nasrin','sree','mathi','asina','hazina','bisrul'],
    'Degree':['B.E','null','null','B.E','B.SC','B.COM']
})
df1

Name Degree
0  nasrin    B.E
1    sree   null
2   mathi   null
3   asina    B.E
4  hazina   B.SC
5  bisrul  B.COM

In [160]:
df1.index

RangeIndex(start=0, stop=6, step=1)

In [161]:
df1.values

array([['nasrin', 'B.E'],
       ['sree', 'null'],
       ['mathi', 'null'],
       ['asina', 'B.E'],
       ['hazina', 'B.SC'],
       ['bisrul', 'B.COM']], dtype=object)

In [162]:
df1.sort_values(by='Name')


Name Degree
3   asina    B.E
5  bisrul  B.COM
4  hazina   B.SC
2   mathi   null
0  nasrin    B.E
1    sree   null

In [163]:
#merging the data frames
df1=DataFrame({'col1': np.arange(6),'Column':['A','B','C','D','E','F']})
df1

col1 Column
0     0      A
1     1      B
2     2      C
3     3      D
4     4      E
5     5      F

In [164]:
df2=DataFrame({'col2':np.arange(1,4),'Column':['A','G','C']})
df2

col2 Column
0     1      A
1     2      G
2     3      C

In [165]:
#join the common coloumn
pd.merge(df1,df2)


col1 Column  col2
0     0      A     1
1     2      C     3

In [166]:
pd.merge(df1,df2,on='Column')


col1 Column  col2
0     0      A     1
1     2      C     3

In [167]:
pd.merge(df1,df2,on='col2')


KeyError: 'col2'

In [94]:
pd.merge(df1,df2,on='Column',how='left')


col1 Column  col2
0     0      A   1.0
1     1      B   NaN
2     2      C   3.0
3     3      D   NaN
4     4      E   NaN
5     5      F   NaN

In [101]:
pd.merge(df1,df2,on='Column',how='right')

col1 Column  col2
0   0.0      A     1
1   NaN      G     2
2   2.0      C     3

In [102]:
pd.merge(df1,df2,on='Column',how='outer')

col1 Column  col2
0   0.0      A   1.0
1   1.0      B   NaN
2   2.0      C   3.0
3   3.0      D   NaN
4   4.0      E   NaN
5   5.0      F   NaN
6   NaN      G   2.0

In [100]:
pd.merge(df1,df2,left_on='col1',right_on='col2')


col1 Column_x  col2 Column_y
0     1        B     1        A
1     2        C     2        G
2     3        D     3        C

In [135]:
df=ar1.reshape(2,4)
df

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

In [172]:
df1=DataFrame(ar1,index=['R1','R2'],columns=['C1','C2','C3','C4'])
df1


C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7